# Generated by Django 6.0.1 on 2026-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_parent", models.CharField(max_length=100)),
                ("email_parent", models.EmailField(max_length=254)),
                ("tel_parent", models.CharField(max_length=20)),
                ("nom_eleve", models.CharField(max_length=100)),
                (
                    "formation",
                    models.CharField(
                        choices=[
                            ("SEC_BUR", "Secrétariat Bureautique et Maintenance"),
                            ("INFOG", "Infographie et Motion Design"),
                            ("DEV_WEB", "Développement Web et Mobile"),
                            (
                                "IA_SYS",
                                "Intelligence Artificielle et Système Intelligent",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("capture_paiement", models.ImageField(upload_to="paiements/")),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("valide", models.BooleanField(default=False)),
            ],
        ),
    ]
